-- MySQL Script generated by MySQL Workbench
-- Sat Jul 14 21:45:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Biblioteka_Fakulteta
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Biblioteka_Fakulteta` ;

-- -----------------------------------------------------
-- Schema Biblioteka_Fakulteta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Biblioteka_Fakulteta` DEFAULT CHARACTER SET utf8 ;
USE `Biblioteka_Fakulteta` ;

-- -----------------------------------------------------
-- Table `Biblioteka_Fakulteta`.`korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Biblioteka_Fakulteta`.`korisnik` ;

CREATE TABLE IF NOT EXISTS `Biblioteka_Fakulteta`.`korisnik` (
  `id_korisnik` INT NOT NULL,
  `korisnicko_ime` VARCHAR(45) NOT NULL,
  `lozinka` VARCHAR(45) NOT NULL,
  `ime` VARCHAR(45) NULL,
  `prezime` VARCHAR(45) NULL,
  `tip_korisnika` VARCHAR(15) NULL,
  `telefon` VARCHAR(25) NULL,
  `e_mail` VARCHAR(45) NULL,
  `status` VARCHAR(10) NULL,
  PRIMARY KEY (`id_korisnik`),
  UNIQUE INDEX `korisnicko_ime_UNIQUE` (`korisnicko_ime` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Biblioteka_Fakulteta`.`kategorija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Biblioteka_Fakulteta`.`kategorija` ;

CREATE TABLE IF NOT EXISTS `Biblioteka_Fakulteta`.`kategorija` (
  `id_kategorija` INT NOT NULL,
  `naziv` VARCHAR(45) NULL,
  `opis` VARCHAR(145) NULL,
  PRIMARY KEY (`id_kategorija`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteka_Fakulteta`.`izdavac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Biblioteka_Fakulteta`.`izdavac` ;

CREATE TABLE IF NOT EXISTS `Biblioteka_Fakulteta`.`izdavac` (
  `id_izdavac` INT NOT NULL,
  `naziv` VARCHAR(45) NULL,
  `opis` VARCHAR(145) NULL,
  `tip_knjige` VARCHAR(45) NULL,
  `adresa_izdavaca` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  PRIMARY KEY (`id_izdavac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteka_Fakulteta`.`knjiga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Biblioteka_Fakulteta`.`knjiga` ;

CREATE TABLE IF NOT EXISTS `Biblioteka_Fakulteta`.`knjiga` (
  `id_knjiga` INT NOT NULL,
  `naziv` VARCHAR(45) NULL,
  `opis` VARCHAR(145) NULL,
  `link_izdavaca` VARCHAR(45) NULL,
  `slika_naslovne` VARCHAR(150) NULL,
  `izdanje` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `kategorija_id_kategorija` INT NOT NULL,
  `izdavac_id_izdavac` INT NOT NULL,
  PRIMARY KEY (`id_knjiga`, `kategorija_id_kategorija`, `izdavac_id_izdavac`),
  INDEX `fk_knjiga_kategorija_idx` (`kategorija_id_kategorija` ASC),
  INDEX `fk_knjiga_izdavac1_idx` (`izdavac_id_izdavac` ASC),
  CONSTRAINT `fk_knjiga_kategorija`
    FOREIGN KEY (`kategorija_id_kategorija`)
    REFERENCES `Biblioteka_Fakulteta`.`kategorija` (`id_kategorija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_knjiga_izdavac1`
    FOREIGN KEY (`izdavac_id_izdavac`)
    REFERENCES `Biblioteka_Fakulteta`.`izdavac` (`id_izdavac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Biblioteka_Fakulteta`.`izdata_knjiga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Biblioteka_Fakulteta`.`izdata_knjiga` ;

CREATE TABLE IF NOT EXISTS `Biblioteka_Fakulteta`.`izdata_knjiga` (
  `id_izdate_knjige` INT NOT NULL AUTO_INCREMENT,
  `dat_vreme_zaduzenja` VARCHAR(45) NULL,
  `rok_za_vracanje` VARCHAR(45) NULL,
  `br_zaduzenih_knjiga` VARCHAR(45) NULL,
  `korisnik_id_korisnik` INT NOT NULL,
  `knjiga_id_knjiga` INT NOT NULL,
  `knjiga_kategorija_id_kategorija` INT NOT NULL,
  `knjiga_izdavac_id_izdavac` INT NOT NULL,
  PRIMARY KEY (`id_izdate_knjige`, `korisnik_id_korisnik`, `knjiga_id_knjiga`, `knjiga_kategorija_id_kategorija`, `knjiga_izdavac_id_izdavac`),
  INDEX `fk_izdate_knjige_korisnik1_idx` (`korisnik_id_korisnik` ASC),
  INDEX `fk_izdate_knjige_knjiga1_idx` (`knjiga_id_knjiga` ASC, `knjiga_kategorija_id_kategorija` ASC, `knjiga_izdavac_id_izdavac` ASC),
  CONSTRAINT `fk_izdate_knjige_korisnik1`
    FOREIGN KEY (`korisnik_id_korisnik`)
    REFERENCES `Biblioteka_Fakulteta`.`korisnik` (`id_korisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_izdate_knjige_knjiga1`
    FOREIGN KEY (`knjiga_id_knjiga` , `knjiga_kategorija_id_kategorija` , `knjiga_izdavac_id_izdavac`)
    REFERENCES `Biblioteka_Fakulteta`.`knjiga` (`id_knjiga` , `kategorija_id_kategorija` , `izdavac_id_izdavac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteka_Fakulteta`.`clanska_karta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Biblioteka_Fakulteta`.`clanska_karta` ;

CREATE TABLE IF NOT EXISTS `Biblioteka_Fakulteta`.`clanska_karta` (
  `broj_clanarine` VARCHAR(45) NULL,
  `id_clanska_karta` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `dat_poslednje_uplate` VARCHAR(45) NULL,
  `pocetak_vazenja` VARCHAR(45) NULL,
  `kraj_vazenja` VARCHAR(45) NULL,
  `tip_clanarine` VARCHAR(45) NULL,
  `korisnik_id_korisnik` INT NOT NULL,
  PRIMARY KEY (`id_clanska_karta`, `korisnik_id_korisnik`),
  INDEX `fk_clanska_karta_korisnik1_idx` (`korisnik_id_korisnik` ASC),
  CONSTRAINT `fk_clanska_karta_korisnik1`
    FOREIGN KEY (`korisnik_id_korisnik`)
    REFERENCES `Biblioteka_Fakulteta`.`korisnik` (`id_korisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE `biblioteka_fakulteta`.`novi_korisnik` (
  `idnovi_korisnik` INT NOT NULL AUTO_INCREMENT,
  `korisnicko_ime` VARCHAR(45) NOT NULL,
  `lozinka` VARCHAR(45) NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `tip_korisnika` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idnovi_korisnik`));

ALTER TABLE `biblioteka_fakulteta`.`knjiga`  CHANGE COLUMN `slika_naslovne` `slika_naslovne` LONGBLOB NULL DEFAULT NULL;
ALTER TABLE `biblioteka_fakulteta`.`knjiga` 
CHANGE COLUMN `opis` `opis` VARCHAR(1450) NULL DEFAULT NULL ,
CHANGE COLUMN `link_izdavaca` `link_izdavaca` VARCHAR(450) NULL DEFAULT NULL ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
